version:  '3'

services:

  weather-report-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=weather_report_dev
      - POSTGRES_USER=weather_report_dev
      - POSTGRES_PASSWORD=weather_report_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data:
